// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with `Firebase.initializeApp()`.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk3CO9JwrKaH5wQHX0qL1mNxYEupkVAgM',
    appId: '1:537414522632:android:465a5331e322e765a23ebd',
    messagingSenderId: '537414522632',
    projectId: 'zoomoman-67957',
    storageBucket: 'zoomoman-67957.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDj4P7KJak3iiid4xIqCO49HQrkLkEYy0',
    appId: '1:537414522632:ios:7cfb7425524cd4dba23ebd',
    messagingSenderId: '537414522632',
    projectId: 'zoomoman-67957',
    storageBucket: 'zoomoman-67957.firebasestorage.app',
    iosBundleId: 'com.zoom.zoomProvider',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc5QdMBZofeglWpFZo-2CIzLQZeNEpIxw',
    appId: '1:537414522632:web:2b9950f9db6bedb4a23ebd',
    messagingSenderId: '537414522632',
    projectId: 'zoomoman-67957',
    authDomain: 'zoomoman-67957.firebaseapp.com',
    storageBucket: 'zoomoman-67957.firebasestorage.app',
    measurementId: 'G-BJ175Q9K2K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDj4P7KJak3iiid4xIqCO49HQrkLkEYy0',
    appId: '1:537414522632:ios:e71525402cb34127a23ebd',
    messagingSenderId: '537414522632',
    projectId: 'zoomoman-67957',
    storageBucket: 'zoomoman-67957.firebasestorage.app',
    iosBundleId: 'com.example.zoomProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc5QdMBZofeglWpFZo-2CIzLQZeNEpIxw',
    appId: '1:537414522632:web:74d6245c31c2b90da23ebd',
    messagingSenderId: '537414522632',
    projectId: 'zoomoman-67957',
    authDomain: 'zoomoman-67957.firebaseapp.com',
    storageBucket: 'zoomoman-67957.firebasestorage.app',
    measurementId: 'G-18RVDL4855',
  );

}